version: '3.4'

services:
  nginx:
    restart: unless-stopped
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_certs:/etc/nginx/certs:ro"
    depends_on:
      - vralumglassweb
    networks:
      - glass-net

  nginx-gen:
    restart: unless-stopped
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_certs:/etc/nginx/certs:ro"
    depends_on:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - glass-net
       
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_certs:/etc/nginx/certs:rw"
    depends_on:
      - nginx-gen
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx
      ACME_CA_URI: ${ACME_CA_URI:-https://acme-staging.api.letsencrypt.org/directory}
    networks:
      - glass-net
         
  vralumglassweb:
    container_name: web
    image: ${DOCKER_REGISTRY-}web
    restart: unless-stopped
    build:
      context: .
      dockerfile: VralumGlassWeb/Dockerfile
    environment:
      VIRTUAL_NETWORK: nginx-proxy
      #VIRTUAL_PORT: 80
      VIRTUAL_HOST: coronaglass.ddns.net
      SSL_POLICY: Mozilla-Modern
      #LETSENCRYPT_HOST: coronaglass.ddns.net
      #LETSENCRYPT_EMAIL: dravgust@hotmail.com
    volumes:
      - ./logs/web:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - glass-net

  postgres:
    container_name: postgres
    image: postgres:11.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "1q2w3e4r"
    volumes:
      - postgres_datadir:/var/lib/postgresql/data
      - ./db/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    networks:
      - glass-net
    ports:
      - "5432:5432"
      
  redis:
    container_name: redis
    image: redis:5.0.3
    restart: unless-stopped
    networks:
      - glass-net

networks:
    glass-net:
      driver: bridge

volumes:
    nginx_conf:
    nginx_vhost:
    nginx_html:
    nginx_certs:
    nginx_htpasswd:
    postgres_datadir:
    