version: '3.4'

services:
  vralumglassweb:
    container_name: "glass-web"
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: VralumGlassWeb/Dockerfile
    volumes:
      - ./logs/web:/app/logs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "postgres"
    networks:
      - glass-network

  postgres:
    container_name: "glass-postgredb"
    image: postgres
    restart: always
    #build:
     # context: .
      #dockerfile: db/Dockerfile
    environment:
      POSTGRES_PASSWORD: "1q2w3e4r"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    networks:
      - glass-network
    ports:
      - "5432:5432"

networks:
    glass-network:
      driver: bridge

volumes:
    db-data:
        driver: local
    