version: '3.4'

services:
  vralumglassweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=0
    ports:
      - "17172:80"